# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd10dca868bef40381b15f7dd49a1711919bbd94493be940000a7fd4aa127aa17213f53b24bff58996e66cc2d057e1c0dd8aa17cf76e9cf9788ed1e7d44e10a

test:
  secret_key_base: 1d129620eccf74ff025204dbac29033ab7147e48274d3322a1dc4b08ee647983016d34a921ab5ea9354c70025b280438fbcb2c47bf76aca8a11bbdd53a796d81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
